# Generated by Django 5.2.3 on 2025-06-20 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0005_task_is_completed_alter_subject_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='schoolapp.student'),
        ),
    ]
